language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  on:
    branch: master
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
