language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm i
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
