export { isString } from './is-string'
export { isNumber } from './is-number'
export { isBoolean } from './is-boolean'
export { isNull } from './is-null'
export { isObject } from './is-object'
export { isArray } from './is-array'
